### ISSUE TITLE
Allow time-1.12

### ISSUE THREAD

**Issue by andreasabel** [haskell-cryptography/HsOpenSSL#67]
Currently, dependency `time-1.12` is excluded by the upper bound:
https://github.com/haskell-cryptography/HsOpenSSL/blob/5099c3b2ecc3ffb6549bf5d4ada406ef6652efe4/HsOpenSSL.cabal#L79

I tested GHC 9.4 buildability successfully, allowing newer `time`:
```
$ cabal install HsOpenSSL-0.11.7.2 --allow-newer=HsOpenSSL:{template-haskell,time} --allow-newer='hsc2hs:*'
Warning: Unknown/unsupported 'ghc' version detected (Cabal 3.7.0.0 supports
'ghc' version < 9.4): /usr/local/bin/ghc is version 9.4.0.20220523
```

**Comment by vshabanov** [comment]
Relaxed upper bound to <1.13 in both the sources and in the new Hackage revision.
