### ISSUE TITLE
Improve suggestions when OpenSSL is not found

### ISSUE THREAD

**Issue by Bodigrim** [haskell-cryptography/HsOpenSSL#75]
https://github.com/haskell-cryptography/HsOpenSSL/blob/094f7ef6c9ef4dc3eea56802382b1d50c99572d6/Setup.hs#L90-L95

This advice works when you build `HsOpenSSL` itself, but does not when `HsOpenSSL` is only a dependency of the current package: `--extra-include-dirs` and `--extra-lib-dirs` are applied only to the current package. A more robust suggestion would be to extend `cabal.project` with

```cabal
package HsOpenSSL
  extra-lib-dirs: ...
  extra-include-dirs: ...
```

**Comment by vshabanov** [comment]
Thank you for the idea. Fixed in HsOpenSSL-0.11.7.5

**Comment by andreasabel** [comment]
While maybe helpful for cabal users. This is lop-sided on the side of cabal vs. stack and causes
- https://github.com/commercialhaskell/stack/issues/6578

I think libraries should be agnostic whether one uses cabal or stack to build them.

**Comment by vshabanov** [comment]
I never used Stack, so I don't know what instructions for Stack might be (and whether is it possible to detect that Cabal is run from stack).
